# NovaSMP Server Properties

server-name=NovaSMP

motd=<gradient:#8A2BE2:#00BFFF><bold>NovaSMP</bold></gradient>\n<gray>Explore • Build • Survive</gray>

server-port=25565

gamemode=survival
difficulty=hard
hardcore=false

online-mode=true
white-list=false

max-players=100

pvp=true
enable-command-block=true

view-distance=8
simulation-distance=6

spawn-protection=0

allow-flight=true

enforce-secure-profile=true
